# Generated by Django 3.0.3 on 2021-04-09 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('date_time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tick_size', models.DecimalField(decimal_places=2, max_digits=8)),
                ('settlement', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
