# Generated by Django 3.0.3 on 2021-04-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
