# Generated by Django 3.0.3 on 2021-04-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='multiplier',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
