# Generated by Django 3.0.3 on 2021-04-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210410_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='max_value',
            new_name='max_price',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='min_value',
            new_name='min_price',
        ),
    ]
