# Generated by Django 3.0.3 on 2021-04-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210417_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Event'),
            preserve_default=False,
        ),
    ]
