# Generated by Django 3.0.3 on 2021-04-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210417_1316'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_event_name'),
        ),
    ]
