# Generated by Django 3.0.3 on 2021-04-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210417_1319'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_event_name',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_user_per_group'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_event_name_per_group'),
        ),
    ]
