# Generated by Django 3.0.3 on 2021-04-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210417_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
