# Generated by Django 3.0.3 on 2021-04-19 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_auto_20210418_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('profitLoss', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
