# Generated by Django 3.0.3 on 2021-04-26 01:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210419_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='market',
            name='position_limit',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='market',
            name='tick_size',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
