# Generated by Django 3.0.3 on 2021-04-26 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210426_0147'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_user_per_group',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='market',
            name='position_limit',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_account_user_per_group'),
        ),
        migrations.AddConstraint(
            model_name='marketposition',
            constraint=models.UniqueConstraint(fields=('market', 'user'), name='unique_position_per_market_user'),
        ),
    ]
